# -*- coding: utf-8 -*-
"""Dash Temperature.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Aezw5NKoxbaFL-TPAICerumvGN2QKDO
"""

!pip install jupyter_dash
!pip install dash

from jupyter_dash import JupyterDash
from dash import html, dcc, dash_table

app = JupyterDash(__name__)

app.layout =html.Div(children=[
  html.Div([
    html.H1('Weather Station, Temperature measure in Cº')
    ]),
  html.Div(children=[
    html.Iframe(src="https://thingspeak.com/channels/2190017/charts/1?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&type=line&update=15",
      style={'display': 'block','border-style':'none',"width": "700px","height":"400px", "border": "1px solid"},
      allow="fullscreen"),
  ])
])
#Execution
app.run_server(debug=False, mode='external', port=8060)